# Generated by Django 3.1.6 on 2021-02-25 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
