# Generated by Django 3.1.6 on 2021-02-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='img',
        ),
    ]
