# Generated by Django 3.1.6 on 2021-02-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_remove_location_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='img',
            field=models.ImageField(default='', upload_to='travelapp/images/places'),
        ),
    ]
