# Generated by Django 3.1.6 on 2021-02-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0010_auto_20210227_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
