# Generated by Django 4.0.2 on 2022-02-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0011_auto_20210227_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='Category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='img',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
